services:
  postgres:
    image: postgres:16
    container_name: scoot-rent
    environment:
      POSTGRES_USER: noleg
      POSTGRES_PASSWORD: root
      POSTGRES_DB: scoot_rent_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
