services:

  app:
    container_name: scoot_rent_app
    image: scootrent-app:latest
    ports:
      - "${BACKEND_PORT}:8080"
    environment:
      SPRING_DATASOURCE_URL: ${DATASOURCE_URL}
      SPRING_DATASOURCE_USERNAME: ${DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${DATASOURCE_PASSWORD}
      TOKEN_SIGNING_KEY: ${TOKEN_SIGNING_KEY}
      TOKEN_EXPIRATION: ${TOKEN_EXPIRATION}
      DEFAULT_ADMIN_PASSWORD: ${DEFAULT_ADMIN_PASSWORD}
      DEFAULT_USER_PASSWORD: ${DEFAULT_USER_PASSWORD}
    depends_on:
      db:
        condition: service_healthy

  db:
    container_name: scoot_rent_database_postgres
    image: postgres:16
    restart: always
    environment:
      POSTGRES_DB: ${DATASOURCE_NAME}
      POSTGRES_USER: ${DATASOURCE_USERNAME}
      POSTGRES_PASSWORD: ${DATASOURCE_PASSWORD}
    ports:
      - "${POSTGRES_PORT}:5432"
    healthcheck:
      test: [ "CMD-SHELL", "psql -U ${DATASOURCE_USERNAME} -d ${DATASOURCE_NAME} -c 'SELECT 1'" ]
      interval: 5s
      timeout: 5s
      retries: 10
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
