spring:
  datasource:
#    TODO не забыть исправить на db
    url: jdbc:postgresql://0.0.0.0:5432/scootrent_db
    password: root
    username: noleg
    driver-class-name: org.postgresql.Driver
  flyway:
    enabled: false
    locations: classpath:db/migration
    baseline-on-migrate: true

logging:
  level:
    root: INFO
    org.springframework.transaction: TRACE
    ru.noleg.scootrent: DEBUG
    org.hibernate.SQL: ERROR
    org.hibernate.tool.schema: ERROR
  file:
    name: logs/scootrent.log
  pattern:
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

subscription:
  overused:
    pricePerMinute: 1.01