spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/scoot_rent_db_docker_test
    password: root
    username: noleg
    driver-class-name: org.postgresql.Driver

  # TODO эти настройки игнорируются
  #  jpa:
  #    hibernate:
  #      ddl-auto: create-drop
  #    show-sql: true
  #    properties:
  #      hibernate:
  #        format_sql: true

  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true

subscription:
  overused:
    pricePerMinute: 1.01

logging:
  level:
    ru.noleg.scootrent: DEBUG
    org.hibernate.SQL: ERROR
    org.hibernate.tool.schema: ERROR
  file:
    name: logs/scootrent.log
  pattern:
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
