spring:
  datasource:
    url: jdbc:postgresql://db/scootrent_db
    password: root
    username: noleg
    driver-class-name: org.postgresql.Driver
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true

logging:
  level:
    root: INFO
    ru.noleg.scootrent: INFO
    org.hibernate.SQL: ERROR
    org.hibernate.tool.schema: ERROR
  file:
    name: logs/scootrent.log
  pattern:
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

subscription:
  overused:
    pricePerMinute: 1.01

token:
  signing:
    key: ${TOKEN_SINGING_KEY:53A73E5F1C4E0A2D3B5F2D784E6A1B423D6F247D1F6E5C3A596D635A75327855}
  expiration: ${TOKEN_EXPIRATION:3600000}

app:
  admin:
    password: ${DEFAULT_ADMIN_PASSWORD:admin123}
  moderator:
    password: ${DEFAULT_MODERATOR_PASSWORD:moderator123}