CREATE TABLE t_user
(
    c_id               BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    c_date_of_birthday DATE,
    c_email            VARCHAR(50) NOT NULL UNIQUE,
    c_password         VARCHAR(255),
    c_phone            VARCHAR(16) NOT NULL UNIQUE,
    c_role             VARCHAR(30) CHECK (c_role IN ('ROLE_ADMIN', 'ROLE_USER', 'ROLE_MODERATOR')),
    c_username         VARCHAR(50) NOT NULL UNIQUE
);