CREATE TABLE t_tariff
(
    c_id                BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    c_duration_unit     VARCHAR(30) CHECK (c_duration_unit IN ('HOUR', 'DAY', 'WEEK', 'MONTH', 'YEAR')),
    c_duration_value    INTEGER,
    c_is_active         BOOLEAN,
    c_price_per_unit    DECIMAL(10, 2),
    c_sub_duration_days INTEGER,
    c_title             VARCHAR(50) NOT NULL,
    c_type              VARCHAR(30) NOT NULL CHECK (c_type IN ('DEFAULT_TARIFF', 'SPECIAL_TARIFF', 'SUBSCRIPTION')),
    c_billing_mode      VARCHAR(30) NOT NULL CHECK (c_billing_mode IN ('PER_HOUR', 'PER_MINUTE')),
    c_unlock_fee        INTEGER,
    c_valid_from        TIMESTAMP(6),
    c_valid_until       TIMESTAMP(6)
);

CREATE INDEX idx_tariff_type_and_billing_mode ON t_tariff (c_type, c_billing_mode);
CREATE INDEX idx_tariff_is_active ON t_tariff (c_is_active);

