CREATE TABLE t_user_tariffs
(
    c_id                      BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    c_custom_price_per_minute DECIMAL(10, 2),
    c_discount_pct            INTEGER,
    c_start_date              TIMESTAMP(6),
    c_end_date                TIMESTAMP(6),
    c_tariff_id               BIGINT NOT NULL,
    c_user_id                 BIGINT NOT NULL,

    CONSTRAINT fk_user_tariff_tariff FOREIGN KEY (c_tariff_id) REFERENCES t_tariff (c_id) ON DELETE CASCADE,
    CONSTRAINT fk_user_tariff_user FOREIGN KEY (c_user_id) REFERENCES t_user (c_id) ON DELETE CASCADE
);

CREATE INDEX idx_user_tariff_tariff_id ON t_user_tariffs (c_tariff_id);
CREATE INDEX idx_user_tariff_user_time ON t_user_tariffs (c_user_id, c_start_date, c_end_date);

